import { describe, it, expect } from 'vitest'

import { derivePrimaryCase } from '../primaryCase'

// F5.3 — the trust-hardened hierarchy: a REAL/STATIC rationale leads (never the
// generated ff_take); the generated ff_take is a separate editorial impression; the
// match % becomes a qualitative band; no raw percentage is returned for rendering.

const HEADER_WARM = {
  eyebrow: 'Why this fits you',
  headline: 'Signals from your last 20 films.',
  rationale: 'Mood overlap, director history, and runtime patterns.',
}
const HEADER_COLD = {
  eyebrow: 'Editorial fingerprint',
  headline: 'How this film reads.',
  rationale: 'Rate 5+ films to unlock personalized matching.',
}

describe('derivePrimaryCase — F5.3 trust hierarchy', () => {
  it('1. adaptive personalized rationale WINS over generated ff_take', () => {
    const r = derivePrimaryCase({
      ffTake: { body: 'A class war told as a home invasion.', byline: 'FeelFlick take' },
      whyHeader: HEADER_WARM, matchPct: 94, signedIn: true,
    })
    expect(r.tier).toBe('adaptive_reason')
    expect(r.primaryLead).toBe(HEADER_WARM.rationale)   // the real rationale leads
    expect(r.primaryLabel).toBe('Why this fits you')
    expect(r.primaryProvenance).toBe('derived')
  })

  it('2. ff_take is returned SEPARATELY as a generated editorial impression', () => {
    const r = derivePrimaryCase({
      ffTake: { body: 'A class war.', byline: 'FeelFlick take' },
      whyHeader: HEADER_WARM, matchPct: 80, signedIn: true,
    })
    expect(r.editorialImpression).toBe('A class war.')
    expect(r.editorialLabel).toBe('FeelFlick impression')
  })

  it('3. the static cold rationale stays primary (static/direct)', () => {
    const r = derivePrimaryCase({ ffTake: null, whyHeader: HEADER_COLD, signedIn: false })
    expect(r.tier).toBe('standalone')
    expect(r.primaryLead).toBe(HEADER_COLD.rationale)
    expect(r.primaryProvenance).toBe('static')
  })

  it('4. generated-only state is labelled an impression, not a personalized fit', () => {
    const r = derivePrimaryCase({ ffTake: { body: 'A quiet stunner.' }, whyHeader: { rationale: '' } })
    expect(r.tier).toBe('generated_impression')
    expect(r.primaryLead).toBe('')                       // no personalized lead
    expect(r.primaryLabel).toBe('FeelFlick impression')
    expect(r.editorialImpression).toBe('A quiet stunner.')
    expect(r.primaryLabel).not.toMatch(/why this fits you/i)
  })

  it('5. a custom generated byline is no longer used as an authority label', () => {
    const r = derivePrimaryCase({ ffTake: { body: 'x', byline: 'Some Critic' }, whyHeader: { rationale: '' } })
    expect(r.editorialLabel).toBe('FeelFlick impression') // fixed, not the byline
    expect(JSON.stringify(r)).not.toContain('Some Critic')
  })

  it('6. the fit band derives correctly from the match %', () => {
    expect(derivePrimaryCase({ whyHeader: HEADER_WARM, matchPct: 92 }).fitBand).toBe('Exceptional fit')
    expect(derivePrimaryCase({ whyHeader: HEADER_WARM, matchPct: 80 }).fitBand).toBe('Strong fit')
    expect(derivePrimaryCase({ whyHeader: HEADER_WARM, matchPct: 64 }).fitBand).toBe('Good fit')
    expect(derivePrimaryCase({ whyHeader: HEADER_WARM, matchPct: 55 }).fitBand).toBeNull()
  })

  it('7. NO raw match percentage is returned for rendering', () => {
    const r = derivePrimaryCase({ whyHeader: HEADER_WARM, matchPct: 84, moodTags: ['tense'], fitProfile: 'arthouse' })
    expect(JSON.stringify(r)).not.toContain('84')
    expect('hasMatch' in r).toBe(false)
    expect(JSON.stringify(r)).not.toContain('%')
  })

  it('8. chips are unchanged (first mood tag + fit profile, capitalized)', () => {
    const r = derivePrimaryCase({ whyHeader: HEADER_WARM, moodTags: ['tense', 'dark'], fitProfile: 'prestige_drama' })
    expect(r.chips).toEqual(['Tense', 'Prestige drama'])
  })

  it('9. the nudge stays honest: signed-out + only a generated impression', () => {
    expect(derivePrimaryCase({ ffTake: { body: 'x' }, whyHeader: HEADER_WARM, signedIn: false }).showNudge).toBe(true)
    expect(derivePrimaryCase({ ffTake: { body: 'x' }, whyHeader: HEADER_WARM, signedIn: true }).showNudge).toBe(false)
    expect(derivePrimaryCase({ ffTake: null, whyHeader: HEADER_COLD, signedIn: false }).showNudge).toBe(false)
  })

  it('10. fully empty input → empty tier, self-hides', () => {
    const r = derivePrimaryCase({ ffTake: null, whyHeader: { rationale: '' }, matchPct: null })
    expect(r.tier).toBe('empty')
    expect(r.shouldRender).toBe(false)
  })

  it('signals-only: a band/chips with no rationale renders under a neutral label', () => {
    const r = derivePrimaryCase({ ffTake: null, whyHeader: { rationale: '' }, matchPct: 80, moodTags: ['tense'] })
    expect(r.tier).toBe('signals_only')
    expect(r.primaryLabel).toBe('How it may fit')
    expect(r.fitBand).toBe('Strong fit')
    expect(r.shouldRender).toBe(true)
  })

  it('a bare sub-60 match with nothing else self-hides (no visible fit claim)', () => {
    expect(derivePrimaryCase({ ffTake: null, whyHeader: { rationale: '' }, matchPct: 55 }).shouldRender).toBe(false)
  })
})
