import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'

import PrimaryCaseCard from '../PrimaryCaseCard'

// F5.3 — the trust-hardened PrimaryCase: a real/static rationale leads; the generated
// ff_take renders below as a clearly-FeelFlick impression (no quote grammar, no
// byline); at most one qualitative fit band; NO visible match integer.

const HEADER = {
  eyebrow: 'Why this fits you',
  headline: 'Signals from your library.',
  rationale: 'Mood overlap and runtime patterns, pulled from what you have actually watched.',
}
const COLD = {
  eyebrow: 'Editorial fingerprint',
  headline: 'How this film reads.',
  rationale: 'Sign in to see how it lines up with your library.',
}

describe('PrimaryCaseCard — F5.3 trust framing', () => {
  it('11. renders the warm rationale BEFORE the generated impression', () => {
    const { container } = render(
      <PrimaryCaseCard ffTake={{ body: 'A class war.', byline: 'A Critic' }} whyHeader={HEADER} matchPct={80} signedIn />,
    )
    expect(screen.getByText(HEADER.rationale)).toBeInTheDocument()
    expect(screen.getByText('A class war.')).toBeInTheDocument()
    // the real rationale comes before the generated impression in the DOM
    const text = container.textContent
    expect(text.indexOf(HEADER.rationale)).toBeLessThan(text.indexOf('A class war.'))
  })

  it('12. the generated-impression disclosure is visible', () => {
    render(<PrimaryCaseCard ffTake={{ body: 'A class war.' }} whyHeader={HEADER} signedIn />)
    expect(screen.getByText('FeelFlick impression')).toBeInTheDocument()
    expect(screen.getByText(/generated by feelflick from the film’s available tone and editorial data/i)).toBeInTheDocument()
  })

  it('13. does not render a generated custom byline as authority', () => {
    render(<PrimaryCaseCard ffTake={{ body: 'A class war.', byline: 'The Times' }} whyHeader={HEADER} signedIn />)
    expect(screen.queryByText('The Times')).not.toBeInTheDocument()
  })

  it('14. renders NO integer user-match percentage', () => {
    const { container } = render(
      <PrimaryCaseCard ffTake={null} whyHeader={HEADER} matchPct={84} moodTags={['tense']} signedIn />,
    )
    expect(container.textContent).not.toMatch(/84/)
    expect(container.textContent).not.toMatch(/how it fits your taste so far/i)
  })

  it('15. renders the qualitative fit band once, with the taste-signal gloss', () => {
    render(<PrimaryCaseCard ffTake={null} whyHeader={HEADER} matchPct={84} signedIn />)
    expect(screen.getByText('Strong fit')).toBeInTheDocument()
    expect(screen.getByText(/based on your taste signals so far/i)).toBeInTheDocument()
  })

  it('16. renders no band below 60', () => {
    render(<PrimaryCaseCard ffTake={null} whyHeader={HEADER} matchPct={55} signedIn />)
    expect(screen.queryByText(/good fit|strong fit|exceptional fit/i)).not.toBeInTheDocument()
  })

  it('17. uses NO blockquote / quotation marks for the generated impression', () => {
    const { container } = render(<PrimaryCaseCard ffTake={{ body: 'A class war.' }} whyHeader={HEADER} signedIn />)
    expect(container.querySelector('blockquote')).toBeNull()
    expect(container.textContent).not.toContain('“A class war.”')
  })

  it('18. a generated-only card has a non-personalized accessible name', () => {
    const { container } = render(<PrimaryCaseCard ffTake={{ body: 'A quiet stunner.' }} whyHeader={{ rationale: '' }} signedIn />)
    const section = container.querySelector('section')
    expect(section.getAttribute('aria-label')).toBe('FeelFlick impression')
    expect(section.getAttribute('aria-label')).not.toMatch(/the case for this film/i)
  })

  it('19. the cold/static case stays honest (standalone rationale, no fabricated fit)', () => {
    render(<PrimaryCaseCard ffTake={null} whyHeader={COLD} matchPct={null} signedIn={false} />)
    expect(screen.getByText(COLD.rationale)).toBeInTheDocument()
    expect(screen.getByText('Editorial fingerprint')).toBeInTheDocument()
  })

  it('20. existing descriptive chips remain', () => {
    render(<PrimaryCaseCard ffTake={null} whyHeader={HEADER} matchPct={null} moodTags={['tense']} fitProfile="prestige_drama" signedIn />)
    expect(screen.getByText('Tense')).toBeInTheDocument()
    expect(screen.getByText('Prestige drama')).toBeInTheDocument()
  })

  it('self-hides when there is genuinely no case', () => {
    const { container } = render(<PrimaryCaseCard ffTake={null} whyHeader={{ rationale: '' }} matchPct={null} />)
    expect(container).toBeEmptyDOMElement()
  })

  it('signed-out + generated impression shows the honest personalize nudge', () => {
    render(<PrimaryCaseCard ffTake={{ body: 'A tense ride.' }} whyHeader={HEADER} matchPct={null} signedIn={false} />)
    expect(screen.getByText(/sign in and rate a few films/i)).toBeInTheDocument()
  })
})
