import { describe, it, expect } from 'vitest'
import { render, screen } from '@testing-library/react'

import ViewerNotes from '../ViewerNotes'

// F5.3 — de-authority pass. The generated critic_quotes are invented personas; this
// section now renders them as plain "FeelFlick impressions" prose with an explicit
// generated-content disclosure and NONE of the review grammar (no blockquote, quote
// marks, author, outlet, or "A viewer" persona). The note text + order + count are
// preserved.
describe('ViewerNotes — FeelFlick impressions (F5.3 honest framing)', () => {
  const notes = [
    { quote: 'Tense from frame one.', author: 'A weekend viewer', outlet: 'After one watch' },
    { quote: 'It lingers.', outlet: 'A second look' },
  ]

  it('21. uses the "FeelFlick impressions" heading (not "Viewer notes")', () => {
    render(<ViewerNotes notes={notes} />)
    expect(screen.getByText('FeelFlick impressions')).toBeInTheDocument()
    expect(screen.queryByText('Viewer notes')).not.toBeInTheDocument()
  })

  it('22. renders the generated-content disclosure', () => {
    render(<ViewerNotes notes={notes} />)
    expect(screen.getByText(/generated by feelflick from the film’s tone and editorial data/i)).toBeInTheDocument()
    expect(screen.getByText(/not real viewer or critic reviews/i)).toBeInTheDocument()
  })

  it('23. renders NO <blockquote>', () => {
    const { container } = render(<ViewerNotes notes={notes} />)
    expect(container.querySelector('blockquote')).toBeNull()
  })

  it('24. adds NO quotation marks around the note text', () => {
    const { container } = render(<ViewerNotes notes={notes} />)
    expect(container.textContent).toContain('Tense from frame one.')
    expect(container.textContent).not.toContain('“Tense from frame one.”')
    expect(container.textContent).not.toContain('“')
  })

  it('25. renders NO author', () => {
    render(<ViewerNotes notes={notes} />)
    expect(screen.queryByText('A weekend viewer')).not.toBeInTheDocument()
  })

  it('26. renders NO outlet', () => {
    render(<ViewerNotes notes={notes} />)
    expect(screen.queryByText(/After one watch/)).not.toBeInTheDocument()
    expect(screen.queryByText(/A second look/)).not.toBeInTheDocument()
  })

  it('27. uses NO "A viewer" fallback persona', () => {
    render(<ViewerNotes notes={notes} />)
    expect(screen.queryByText('A viewer')).not.toBeInTheDocument()
  })

  it('28. preserves the generated note prose', () => {
    render(<ViewerNotes notes={notes} />)
    expect(screen.getByText('Tense from frame one.')).toBeInTheDocument()
    expect(screen.getByText('It lingers.')).toBeInTheDocument()
  })

  it('29. preserves note order and count', () => {
    const { container } = render(<ViewerNotes notes={notes} />)
    const grid = container.querySelector('.ff-movie-critic-grid')
    const items = grid.querySelectorAll('p')
    expect(items.length).toBe(2)
    expect(items[0].textContent).toContain('Tense from frame one.')
    expect(items[1].textContent).toContain('It lingers.')
  })

  it('30. self-hides when there are no notes', () => {
    expect(render(<ViewerNotes notes={null} />).container).toBeEmptyDOMElement()
    expect(render(<ViewerNotes notes={[]} />).container).toBeEmptyDOMElement()
  })
})
