name: Daily Movie Discovery

on:
  schedule:
    # Run every day at 6:00 AM UTC (1:00 AM EST / 2:00 AM EDT)
    - cron: '0 6 * * *'
  
  workflow_dispatch:
    # Allow manual trigger with options
    inputs:
      dry_run:
        description: 'Run in dry-run mode (simulate only)'
        required: false
        type: boolean
        default: false
      
      omdb_limit:
        description: 'OMDb quota limit (max movies to fetch ratings for)'
        required: false
        type: number
        default: 100

env:
  NODE_VERSION: '18'

jobs:
  discover:
    name: Discover & Process New Movies
    runs-on: ubuntu-latest
    timeout-minutes: 30
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run daily discovery pipeline
        id: pipeline
        run: |
          if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
            node scripts/pipeline/run-pipeline.js discover --dry-run
          else
            node scripts/pipeline/run-pipeline.js discover
          fi
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true

      - name: Send email notification
        if: always()
        run: node scripts/monitoring/post-pipeline-notification.js --run-id=${{ github.run_number }}
        env:
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          NOTIFICATION_FROM_EMAIL: ${{ secrets.NOTIFICATION_FROM_EMAIL }}
          NOTIFICATION_TO_EMAIL: ${{ secrets.NOTIFICATION_TO_EMAIL }}
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          GITHUB_SERVER_URL: ${{ github.server_url }}
          GITHUB_REPOSITORY: ${{ github.repository }}
          GITHUB_RUN_ID: ${{ github.run_id }}
        continue-on-error: true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: pipeline-logs-${{ github.run_number }}
          path: logs/
          retention-days: 30

      - name: Send success notification
        if: success()
        uses: daun/webhook-action@v1
        with:
          url: ${{ secrets.RESEND_WEBHOOK_URL }}
          data: |
            {
              "type": "pipeline_success",
              "mode": "discover",
              "run_id": "${{ github.run_number }}",
              "timestamp": "${{ github.event.repository.updated_at }}"
            }
        continue-on-error: true

      - name: Send failure notification
        if: failure()
        uses: daun/webhook-action@v1
        with:
          url: ${{ secrets.RESEND_WEBHOOK_URL }}
          data: |
            {
              "type": "pipeline_failure",
              "mode": "discover",
              "run_id": "${{ github.run_number }}",
              "timestamp": "${{ github.event.repository.updated_at }}"
            }
        continue-on-error: true

      - name: Check pipeline status
        if: steps.pipeline.outcome == 'failure'
        run: |
          echo "❌ Pipeline failed. Check logs for details."
          exit 1
