name: Manual Pipeline Run

on:
  workflow_dispatch:
    inputs:
      mode:
        description: 'Pipeline mode'
        required: true
        type: choice
        options:
          - discover
          - refresh
          - deep-refresh
          - full
        default: 'discover'
      
      dry_run:
        description: 'Run in dry-run mode (simulate only)'
        required: false
        type: boolean
        default: false
      
      stop_on_error:
        description: 'Stop pipeline if any step fails'
        required: false
        type: boolean
        default: false

env:
  NODE_VERSION: '18'

jobs:
  manual-run:
    name: Manual Pipeline - ${{ github.event.inputs.mode }}
    runs-on: ubuntu-latest
    timeout-minutes: 180 # 3 hours for full mode
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create logs directory
        run: mkdir -p logs

      - name: Display run configuration
        run: |
          echo "## Manual Pipeline Run Configuration" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Mode:** ${{ github.event.inputs.mode }}" >> $GITHUB_STEP_SUMMARY
          echo "**Dry Run:** ${{ github.event.inputs.dry_run }}" >> $GITHUB_STEP_SUMMARY
          echo "**Stop on Error:** ${{ github.event.inputs.stop_on_error }}" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered by:** @${{ github.actor }}" >> $GITHUB_STEP_SUMMARY
          echo "**Timestamp:** $(date -u '+%Y-%m-%d %H:%M:%S UTC')" >> $GITHUB_STEP_SUMMARY

      - name: Run pipeline
        id: pipeline
        run: |
          FLAGS=""
          if [ "${{ github.event.inputs.dry_run }}" == "true" ]; then
            FLAGS="$FLAGS --dry-run"
          fi
          if [ "${{ github.event.inputs.stop_on_error }}" == "true" ]; then
            FLAGS="$FLAGS --stop-on-error"
          fi
          
          node scripts/pipeline/run-pipeline.js ${{ github.event.inputs.mode }} $FLAGS
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: manual-run-${{ github.event.inputs.mode }}-${{ github.run_number }}
          path: logs/
          retention-days: 90

      - name: Generate summary
        if: always()
        run: |
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "---" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f logs/run-pipeline*.log ]; then
            echo "### Pipeline Execution Log" >> $GITHUB_STEP_SUMMARY
            echo '```
            tail -n 100 logs/run-pipeline*.log >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Send notification
        if: always()
        uses: daun/webhook-action@v1
        with:
          url: ${{ secrets.RESEND_WEBHOOK_URL }}
          data: |
            {
              "type": "manual_pipeline",
              "mode": "${{ github.event.inputs.mode }}",
              "status": "${{ steps.pipeline.outcome }}",
              "triggered_by": "${{ github.actor }}",
              "run_id": "${{ github.run_number }}",
              "dry_run": "${{ github.event.inputs.dry_run }}"
            }
        continue-on-error: true

      - name: Check pipeline status
        if: steps.pipeline.outcome == 'failure'
        run: |
          echo "❌ Pipeline failed. Check logs for details."
          exit 1
