name: Weekly Data Refresh

on:
  schedule:
    # Run every Sunday at 2:00 AM UTC (9:00 PM EST Saturday / 10:00 PM EDT Saturday)
    - cron: '0 2 * * 0'
  
  workflow_dispatch:
    # Allow manual trigger
    inputs:
      metadata_limit:
        description: 'Metadata update limit'
        required: false
        type: number
        default: 500
      
      ratings_limit:
        description: 'OMDb ratings limit'
        required: false
        type: number
        default: 200
      
      embeddings_limit:
        description: 'Embeddings generation limit'
        required: false
        type: number
        default: 200

env:
  NODE_VERSION: '18'

jobs:
  refresh:
    name: Refresh Stale Movie Data
    runs-on: ubuntu-latest
    timeout-minutes: 60
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Create logs directory
        run: mkdir -p logs

      - name: Run weekly refresh pipeline
        id: pipeline
        run: node scripts/pipeline/run-pipeline.js refresh
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
          TMDB_API_KEY: ${{ secrets.TMDB_API_KEY }}
          OMDB_API_KEY: ${{ secrets.OMDB_API_KEY }}
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        continue-on-error: true

      - name: Upload logs
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: weekly-refresh-logs-${{ github.run_number }}
          path: logs/
          retention-days: 90

      - name: Generate summary report
        if: always()
        run: |
          echo "## Weekly Refresh Summary" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          echo "**Run ID:** ${{ github.run_number }}" >> $GITHUB_STEP_SUMMARY
          echo "**Mode:** refresh" >> $GITHUB_STEP_SUMMARY
          echo "**Triggered:** ${{ github.event_name }}" >> $GITHUB_STEP_SUMMARY
          echo "" >> $GITHUB_STEP_SUMMARY
          
          if [ -f logs/run-pipeline*.log ]; then
            echo "### Pipeline Log Preview" >> $GITHUB_STEP_SUMMARY
            echo '```
            tail -n 50 logs/run-pipeline*.log >> $GITHUB_STEP_SUMMARY
            echo '```' >> $GITHUB_STEP_SUMMARY
          fi

      - name: Send notification
        if: always()
        uses: daun/webhook-action@v1
        with:
          url: ${{ secrets.RESEND_WEBHOOK_URL }}
          data: |
            {
              "type": "weekly_refresh",
              "status": "${{ steps.pipeline.outcome }}",
              "run_id": "${{ github.run_number }}",
              "timestamp": "${{ github.event.repository.updated_at }}"
            }
        continue-on-error: true

      - name: Check pipeline status
        if: steps.pipeline.outcome == 'failure'
        run: |
          echo "❌ Weekly refresh failed. Check logs for details."
          exit 1
