import { describe, it, expect, beforeAll, afterAll, vi } from 'vitest'
import { render, screen } from '@testing-library/react'

vi.mock('framer-motion', () => ({ useReducedMotion: () => false }))

import DecisionEvidence from '../DecisionEvidence'

beforeAll(() => { vi.stubGlobal('IntersectionObserver', class { observe() {} unobserve() {} disconnect() {} }) })
afterAll(() => { vi.unstubAllGlobals() })

const WHY_HEADER = { eyebrow: 'Why this fits you', headline: 'Signals from your library.', rationale: 'Mood overlap and runtime.' }
const WHY = [{ id: 'mood-film', icon: 'mood', title: 'Tense', detail: "This film's mood." }]
const AXES = [{ name: 'Intensity', weight: 0.8, hex: '#EF4444' }, { name: 'Pace', weight: 0.6, hex: '#A78BFA' }, { name: 'Range', weight: 0.5, hex: '#FBBF24' }]
const NOTES = [{ quote: 'Tense from frame one.' }]

const full = (over = {}) => render(
  <DecisionEvidence whyHeader={WHY_HEADER} whyReasons={WHY} radarAxes={AXES} viewerNotes={NOTES}
    onHoverReason={() => {}} highlightReasonId={null} highlightMood={null} onHoverAxis={() => {}} {...over} />,
)

describe('DecisionEvidence — consolidated evidence disclosure (F5.5)', () => {
  it('31/32. collapsed by default under a "Why this film" disclosure', () => {
    const { container } = full()
    const details = container.querySelector('details')
    expect(details.open).toBe(false)
    expect(screen.getByText('Why this film')).toBeInTheDocument()
    expect(screen.getByText(/See the signals and tone behind FeelFlick/i)).toBeInTheDocument()
  })

  it('33/34/35. Why For You + Mood profile + FeelFlick impressions render inside when available', () => {
    full()
    expect(screen.getByText('Tense', { selector: '*' })).toBeTruthy()         // Why For You card
    expect(screen.getAllByText('FeelFlick mood profile').length).toBeGreaterThan(0) // Mood profile
    expect(screen.getByText('FeelFlick impressions')).toBeInTheDocument()      // impressions
    expect(screen.getByText('Tense from frame one.')).toBeInTheDocument()
  })

  it('36. missing children are omitted (only Why For You here)', () => {
    full({ radarAxes: null, viewerNotes: null })
    expect(screen.queryByText('FeelFlick mood profile')).not.toBeInTheDocument()
    expect(screen.queryByText('FeelFlick impressions')).not.toBeInTheDocument()
    expect(screen.getByText('Why this film')).toBeInTheDocument()
  })

  it('37. fully empty evidence self-hides (renders nothing)', () => {
    const { container } = render(
      <DecisionEvidence whyHeader={WHY_HEADER} whyReasons={[]} radarAxes={null} viewerNotes={null}
        onHoverReason={() => {}} highlightReasonId={null} highlightMood={null} onHoverAxis={() => {}} />,
    )
    expect(container).toBeEmptyDOMElement()
  })

  it('38. introduces NO fit percentage', () => {
    const { container } = full()
    expect(container.textContent).not.toMatch(/\d+\s*%\s*match/i)
    expect(container.textContent).not.toMatch(/how it fits your taste so far/i)
  })

  it('39/40. no generated-authority grammar; the honest generated disclosures remain', () => {
    const { container } = full()
    expect(container.querySelector('blockquote')).toBeNull() // ViewerNotes stays plain prose
    expect(screen.getByText(/Generated by FeelFlick from the film’s tone and editorial data/i)).toBeInTheDocument()
    expect(screen.getByText(/A generated reading of the film’s tone — not a measured fact/i)).toBeInTheDocument()
  })
})
