// src/features/movie/PrimaryCaseCard.jsx
// The Film File's single leading "case" section.
//
// F5.3 trust hierarchy (see derive/primaryCase.js):
//   • The REAL/STATIC personalized rationale leads (warm "Why this fits you" or the
//     honest cold/standalone line). It is never replaced by the generated ff_take.
//   • The generated ff_take, when present, renders BELOW as a visually-secondary,
//     explicitly FeelFlick-generated impression — plain prose, no quote grammar, no
//     invented byline/outlet, and it never overpowers the real case.
//   • At most ONE qualitative fit band (Good / Strong / Exceptional). No %, no ring,
//     no confidence meter — the precise integer was removed in F5.3.
// EXISTING DATA ONLY · NEVER FABRICATES. Self-hides when nothing useful exists.

import AccentPanel from '@/shared/ui/AccentPanel'
import Eyebrow from '@/shared/ui/Eyebrow'
import { HP, RADIUS, SPACE } from './data'
import { derivePrimaryCase } from './derive/primaryCase'

/**
 * @param {object}  props
 * @param {object|null} props.ffTake     overlay.ff_take ({ body, byline, meta }) or null (GENERATED)
 * @param {object}  props.whyHeader      { eyebrow, headline, rationale } (tier-adaptive)
 * @param {number|null} props.matchPct   engine match % (0–99) or null — mapped to a band, never shown
 * @param {string[]} [props.moodTags]    film mood_tags (descriptive chips)
 * @param {string|null} [props.fitProfile] film fit_profile (descriptive chip)
 * @param {boolean} [props.signedIn]
 * @returns {JSX.Element|null}
 */
export default function PrimaryCaseCard({
  ffTake, whyHeader, matchPct, moodTags = [], fitProfile, signedIn = false,
}) {
  const {
    tier, primaryLabel, primaryLead, editorialImpression, editorialLabel,
    fitBand, chips, showNudge, shouldRender,
  } = derivePrimaryCase({ ffTake, whyHeader, matchPct, moodTags, fitProfile, signedIn })

  if (!shouldRender) return null

  // A real/static case is "the case for this film"; a generated-only card is framed
  // honestly as an impression (not a personalized case).
  const sectionLabel = primaryLead ? 'The case for this film' : primaryLabel
  // Show the primary eyebrow for a real/static lead or a signals-only band — but NOT
  // for the generated-only card (its own "FeelFlick impression" label serves there).
  const showPrimaryHeader = Boolean(primaryLead) || tier === 'signals_only'

  return (
    <section
      aria-label={sectionLabel}
      className="ff-movie-section ff-movie-primary-case"
      style={{ padding: `${SPACE.sectionSm}px ${SPACE.gutter}px 8px`, borderTop: `1px solid ${HP.border}` }}
    >
      <AccentPanel
        variant="gradient"
        tone="purple"
        radius="lg"
        style={{ maxWidth: 880, padding: '26px 30px' }}
      >
        {(showPrimaryHeader || fitBand) && (
          <div style={{ display: 'flex', alignItems: 'center', justifyContent: 'space-between', gap: 16, flexWrap: 'wrap', marginBottom: primaryLead ? 12 : 0 }}>
            {showPrimaryHeader ? <Eyebrow color={HP.purple}>{primaryLabel}</Eyebrow> : <span />}
            {fitBand && (
              <span style={{ display: 'inline-flex', alignItems: 'baseline', gap: 7 }}>
                <span style={{ fontFamily: 'Outfit', fontSize: 14, fontWeight: 700, color: HP.text, letterSpacing: '0.01em' }}>{fitBand}</span>
                <span style={{ fontFamily: 'Outfit', fontSize: 10.5, fontWeight: 600, letterSpacing: '0.08em', textTransform: 'uppercase', color: HP.textMuted }}>
                  based on your taste signals so far
                </span>
              </span>
            )}
          </div>
        )}

        {primaryLead && (
          <p
            style={{
              margin: 0,
              fontFamily: 'Outfit, Inter, sans-serif',
              fontSize: 'clamp(17px, 1.5vw, 21px)',
              lineHeight: 1.5,
              color: HP.text,
              letterSpacing: '-0.01em',
              textWrap: 'pretty',
            }}
          >
            {primaryLead}
          </p>
        )}

        {editorialImpression && (
          <div
            style={{
              marginTop: primaryLead ? 20 : 0,
              paddingTop: primaryLead ? 18 : 0,
              borderTop: primaryLead ? `1px solid ${HP.border}` : 'none',
            }}
          >
            <Eyebrow color={HP.textMuted} style={{ marginBottom: 8 }}>{editorialLabel}</Eyebrow>
            <p style={{ margin: 0, fontFamily: 'Outfit, Inter, sans-serif', fontSize: 'clamp(15px, 1.3vw, 18px)', lineHeight: 1.5, color: HP.textSoft, letterSpacing: '-0.005em', textWrap: 'pretty' }}>
              {editorialImpression}
            </p>
            <p style={{ margin: '10px 0 0 0', fontSize: 11.5, lineHeight: 1.5, color: HP.textMuted, fontFamily: 'Outfit, Inter, sans-serif' }}>
              Generated by FeelFlick from the film’s available tone and editorial data.
            </p>
          </div>
        )}

        {chips.length > 0 && (
          <div style={{ display: 'flex', gap: 8, marginTop: 18, flexWrap: 'wrap' }}>
            {chips.map(c => (
              <span key={c} style={{ padding: '4px 10px', borderRadius: RADIUS.pill, background: 'rgba(255,255,255,0.05)', border: `1px solid ${HP.border}`, fontFamily: 'Outfit', fontSize: 11, fontWeight: 600, letterSpacing: '0.04em', color: HP.textSoft }}>{c}</span>
            ))}
          </div>
        )}

        {showNudge && (
          <p style={{ margin: '16px 0 0 0', fontSize: 12.5, lineHeight: 1.5, color: HP.textMuted, fontFamily: 'Outfit, Inter, sans-serif' }}>
            Sign in and rate a few films to make this fit personal.
          </p>
        )}
      </AccentPanel>
    </section>
  )
}
