// src/features/movie/ViewerNotes.jsx
// FeelFlick impressions (F5.3). These come from `overlay.critic_quotes`, which the
// generate-movie-overlay edge function produces as INVENTED friend-voice personas
// (origin: generated/direct in sourceClassification.js). They are NOT real reviews.
//
// F5.3 de-authority pass: the old "Viewer notes" framing still rendered each item
// with the *grammar of a real review* — a <blockquote>, quotation marks, an author
// byline, and an outlet — which read as attributed critic/viewer quotes despite the
// disclaimer. This phase removes that grammar entirely: a plain "FeelFlick
// impressions" section, an explicit generated-content disclosure, and each note as
// plain prose with NO quote marks, author, outlet, or "A viewer" persona. The note
// text + order + count are preserved; only the misleading presentation changes.
//
// NOTE: the underlying data field stays `critic_quotes` (legacy) — only the visible
// grammar changes in this phase.

import Eyebrow from '@/shared/ui/Eyebrow'
import { HP } from './data'

/**
 * @param {object} props
 * @param {Array<{quote:string, author?:string, outlet?:string}>|null} props.notes
 * @returns {JSX.Element|null}
 */
export default function ViewerNotes({ notes }) {
  if (!notes || notes.length === 0) return null
  return (
    <section className="ff-movie-section" style={{ padding: '48px 88px', borderTop: `1px solid ${HP.border}`, background: 'rgba(255,255,255,0.012)' }}>
      <Eyebrow rule color={HP.purple} style={{ marginBottom: 10 }}>FeelFlick impressions</Eyebrow>
      {/* The honesty line — these are generated, not real reviews. */}
      <p style={{ margin: '0 0 24px 0', fontSize: 12, lineHeight: 1.5, color: HP.textMuted, fontFamily: 'Outfit, Inter, sans-serif', maxWidth: 580 }}>
        Generated by FeelFlick from the film’s tone and editorial data — not real
        viewer or critic reviews.
      </p>
      <div className="ff-movie-critic-grid" style={{ display: 'grid', gridTemplateColumns: '1fr 1fr', gap: 56 }}>
        {notes.map((q, i) => (
          <p
            key={i}
            style={{ margin: 0, fontFamily: 'Outfit, Inter, sans-serif', fontSize: 18, lineHeight: 1.5, color: HP.textSoft, letterSpacing: '-0.012em', textWrap: 'pretty' }}
          >
            {q.quote}
          </p>
        ))}
      </div>
    </section>
  )
}
