-- Film portraits generated by LLM and served post-watch.
-- Written only by the generation script via service role; clients get public read.
create table if not exists film_portraits (
  tmdb_id       integer     primary key,
  portrait      jsonb       not null,
  model         text        not null default 'gpt-4o-mini',
  generated_at  timestamptz not null default now()
);

alter table film_portraits enable row level security;

create policy "Public read"
  on film_portraits
  for select
  using (true);
